### ISSUE TITLE
Build fails with latest pull

### ISSUE THREAD

**Issue by VonSzarvas** [dbetz/Parallax-ESP#29]
Something to do with the recent FCount fix?

Here's make output:

```
build/httpd_app.a(sscp.o):(.data+0x7c): undefined reference to `fs_do_finfo'
build/httpd_app.a(sscp.o):(.data+0x84): undefined reference to `fs_do_fcount'
build/httpd_app.a(sscp.o):(.data+0x8c): undefined reference to `fs_do_frun'
collect2: error: ld returned 1 exit status
Makefile.ota:50: recipe for target 'build/httpd.user1.out' failed
make: *** [build/httpd.user1.out] Error 1
```

**Comment by dbetz** [comment]
Sorry, I just fixed it.

**Comment by VonSzarvas** [comment]
No worries- and very happy you could fix it so quick.

Tested and working great!

**Comment by dbetz** [comment]
It wasn’t really a bug to fix. I had forgotten to check in a new file that contained the filesystem API functions.

**Comment by ClockLoop** [comment]
Thanks for the work on this dbetz, I was able to build this on a raspberrypi 3, as of today.  (Raspbian Stretch with latest updates) 

 (the esp-open-sdk, compiled good too, but ONLY if you don't run this command:   
$ git clone --recursive https://github.com/pfalcon/esp-open-sdk.git  
the --recursive will fail when you go to compile the tool chain, it fails due to missing files)

BUT if you let the makefile gather the files it needs by its self as it goes, the compile of the toolchain will succeed.  Perhaps I just ran into a rare problem, and this isn't the case with others, but...
I succeeded Like this:  
$ git clone https://github.com/pfalcon/esp-open-sdk.git
Not sure why, i know theres nothing u can do about it, just thought id mention it.

EXCELLENT!
(i am able to build open spin, and proploader on the pi3 stretch also!   Thanks!(
